url: https://bellot2020.github.io/bellottechnics
baseurl:

plugins:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
permalink: pretty

# Site settings
title: BELLOT TECHNICS
email: admon@bellottechnicsbm.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/bellottechincs/
  - title: linkedin
    url: https://www.linkedin.com/company/bellottechnicsbm/?originalSubdomain=es
  - title: pinterest
    url: https://www.pinterest.es/bellottechnics/
  - title: twitter
    url: https://twitter.com/BELLOTTECHNICS
  - title: youtube
    url: https://www.youtube.com/user/BELLOTTECHNICS

# Català
lang:
  ca:
    site_description: "Empresa especialitzada en solucions d'etiquetatge i packaging personalitzat per als sectors tèxtil, joieria, complements i alimentació."
    intro1: "Benvinguts al nostre Web!"
    intro2: "UN MÓN DE SOLUCIONS"
    more: "Llegir més"
    close: "Tanca"
    colaborators: "Col·laboradors"
    colaborators_marta: "Fotografia professional"
    colaborators_certificatinos: "Certificació d’Eficiència Energètica"
    services: "Serveis"
    services_description: "Disseny, producció, manipulat i lliurament arreu del món dels nostres productes."
    services_design_title: "Disseny"
    services_design_description: "Dissenyem la marca i el logo, creem tot l'etiquetat de les seves col·leccions."
    services_handled_title: "Manipulats"
    services_handled_description: "Elaborem treballs a la mida de cada client, tant en preu com en qualitat."
    services_delivery_title: "Distribució"
    services_delivery_description: "Col·loquem a qualsevol part del món les seves comandes."
    services_photo_title: "Fotografia de producte"
    services_photo_description: "Oferim tots els serveis fotogràfics que la seva marca necessita."
    products: "Productes"
    products_description: "Trobeu els productes adequats per al vostre negoci i projecte."
    contact: "Contactar"
    contact_name: "El teu nom"
    contact_name_validation: "Introduïu el vostre nom."
    contact_email: "El teu e-mail"
    contact_email_validation: "Introduïu el vostre email."
    contact_phone: "El teu telèfon"
    contact_phone_validation: "Introduïu el vostre telèfon."
    contact_message: "El teu missatge"
    contact_message_validation: "Introduïu el vostre missatge."
    contact_send: "Enviar el missatge"
    privacy: "Privacitat"
    legal: "Avís legal"
    about: "Sobre nosaltres"
    about_description: "Combinant una constant modernització del nostre catàleg junt amb la investigació i desenvolupament de noves solucions de suport en imatge corporativa, a Bellot Technics apostem per un negoci de desenvolupament sostenible, pel benestar dels nostres col·laboradors i la responsabilitat social i del medi-ambient, mirant de sorprendre els nostres clients amb el disseny i la innovació dels nostres productes i serveis, i satisfer i superar les seves expectatives. "
    about_vision: "VISIÓ"
    about_vision_description: "Esdevenir l'empresa que comprèn i satisfà millor les necessitats de producte, servei i identitat d'una marca."
    about_mission: "MISSIÓ"
    about_mission_description: "Superar les expectatives dels nostres clients amb solucions innovadores i personalitzades que donin suport de la seva imatge."
    about_values: "VALORS"
    about_values_description: "CREDIBILITAT - Confiar en els altres i construir relacions basades en la confiança.<br>
                               QUALITAT - Fem les coses de forma simple i eficaç.<br>
                               ATENCIÓ - Fixar-nos fins el més petit detall és imperatiu per aconseguir la perfecció.<br>
                               PASSIÓ - Treballant amb valentia, desafiant l'estatus quo, avançant contínuament, innovant i millorant dia a dia.<br>
                               INNOVACIÓ - Recerca i desenvolupament continu per a crear nous i millors productes.<br>
                               FLEXIBILITAT - Pensant i actuant tenint sempre en compte els nostres clients.<br>"
  es:
    site_description: "Empresa especializada en soluciones de etiquetado y merchandising personalizado para los sectores téxtil, joyería, complementos y alimentación."
    intro1: "Bienvenidos a nuestra Web!"
    intro2: "UN MUNDO DE SOLUCIONES"
    more: "Leer más"
    close: "Cierra"
    colaborators: "Colaboradores"
    colaborators_marta: "Fotografía profesional"
    colaborators_certificatinos: "Certificaciones de Eficiencia Energética"
    services: "Servicios"
    services_description: "Diseño, producción, manipulado i entrega en cualquier destino de nuestros productos."
    services_design_title: "Diseño"
    services_design_description: "Diseñamos su marca y logotipo, creamos todo el etiquetado para sus colecciones."
    services_handled_title: "Manipulados"
    services_handled_description: "Desarrollamos trabajos a medida de cada cliente, tanto en precio com en calidad."
    services_delivery_title: "Distribución"
    services_delivery_description: "Enviamos a cualquier parte del mundo sus pedidos."
    services_photo_title: "Fotografia de producto"
    services_photo_description: "Ofrecemos todos los servicios fotográficos que su marca necesita."
    products: "Productos"
    products_description: "Encuentra los productos adecuados para tu negocio o proyecto."
    contact: "Contactar"
    contact_name: "Tu nombre"
    contact_name_validation: "Escribe tu nombre."
    contact_email: "Tu e-mail"
    contact_email_validation: "Escribe tu e-mail."
    contact_phone: "Tu teléfono"
    contact_phone_validation: "Escribe tu teléfono."
    contact_message: "Tu mensaje"
    contact_message_validation: "Déjanos un mensaje."
    contact_send: "Enviar el mensaje"
    privacy: "Privacidad"
    legal: "Aviso legal"
    about: "Sobre nosotros"
    about_description: "Comabinando una constante modernización de nuestro catálogo junto con la investigación y desarrollo de nuevas soluciones de soporte en imagen corporativa, en Bellot Technics apostamos por un negocio de desarrollo sostenible, por el bienestar de nuestros colaboradores i la responsabilidad social i del medio-ambiente, intentando sorprender a nuestros clientes con el diseño y la innovación de nuestro productos y servicios, así como satisfacer y superar sus expectativas. "
    about_vision: "VISIÓN"
    about_vision_description: "Ser la empresa que comprende y satisface mejor las necesidades de producto, servicio e identidad de una marca."
    about_mission: "MISIÓN"
    about_mission_description: "Superar las expectativas de nuestros clientes con soluciones innovadoras y personalizadas que den soporte a su imagen."
    about_values: "VALORES"
    about_values_description: "CREDIBILIDAD - Confiar en los demás y construir relaciones basadas en la confianza.<br>
                               CALIDAD - Hacemos las cosas de forma simple y eficaz.<br>
                               ATENCIÓN - Cuidar hasta el mínimo detalle es imperativo para conseguir la perfección.<br>
                               PASIÓN - Trabajando con valentía, desafiando el status quo, avanzando contínuamente, innovando y mejorando día tras día.<br>
                               INNOVACIÓN - Búsqueda y desarrollo contínuos para crear nuevos y mejores productos.<br>
                               FLEXIBILIDAD - Pensando y actuando teniendo siempre en cuenta a nuestros clientes.<br>"
  en:
    site_description: "Company specialized in labeling solutions and personalized merchandising for the textile, jewelry, accessories and food sectors"
    intro1: "Welcome to our website!"
    intro2: "A WORLD OF SOLUTIONS"
    more: "Read more"
    close: "Close"
    colaborators: "Partners"
    colaborators_marta: "Professional Photography"
    colaborators_certificatinos: "Certificació d’Eficiència Energètica"
    services: "Services"
    services_description: "Design, production, handling and worldwide delivery."
    services_design_title: "Design"
    services_design_description: "We design your new brand and your new logo, we create all the labeling of your collections."
    services_handled_title: "Hand made"
    services_handled_description: "We make duties tailored to each client, both in price and quality."
    services_delivery_title: "Delivery"
    services_delivery_description: "We deliver your orders anywhere in the world."
    services_photo_title: "Product Photography"
    services_photo_description: "We offer all the photographic services that your brand needs."
    products: "Products"
    products_description: "Find the right products for your business and project."
    contact: "Contact"
    contact_name: "Your name"
    contact_name_validation: "Enter your name."
    contact_email: "Your e-mail"
    contact_email_validation: "Enter your e-mail."
    contact_phone: "Your phone number"
    contact_phone_validation: "Enter your phone number."
    contact_message: "Your message"
    contact_message_validation: "Enter your message."
    contact_send: "Send the message"
    privacy: "Privacy"
    legal: "Legal warning"
    about: "About Us"
    about_description: "Combining a constant modernization of our catalog with the research and development of new solutions of support in corporate image, at Bellot Technics we bet by a business of sustainable development, by the well-being of our partners, the social responsibility of the environement, trying to surprise our customers with the design and innovation of our products and services, to meet and exceed their expectations. "
    about_vision: "VISION"
    about_vision_description: "To be the company that best understands and meets the needs of a brand's product, service and identity – globally."
    about_mission: "MISSION"
    about_mission_description: "To exceed our costumers’ expectations with innovative and customized imaging solutions."
    about_values: "VALUES"
    about_values_description: "CREDIBILITY - Trust in others and build relationships of trust.<br>
                               QUALITY - We do things simply and effectively.<br>
                               ATTENTION - To attend to every detail is imperative.<br>
                               PASSION - Acting with courage, challenging the status quo, steadily advancing, innovating and improving.<br>
                               INNOVATION - We develop continuous research to create new and better products.<br>
                               FLEXIBILITY - Think and act always thinking about our costumers needs.<br>"
